name = "symphony-childcare"
compatibility_date = "2026-01-15"
pages_build_output_dir = ".open-next"

[build]
command = "npx @opennextjs/cloudflare build"

main = ".open-next/worker.js"

[build.upload]
dir = ".open-next/assets"

[env.production.vars]
NODE_ENV = "production"