name = "symphony-childcare"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[env.production]
name = "symphony-childcare"

[env.production.build]
command = "npm run build"